name: terraform-apply

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    # ジョブの出力を定義
    outputs:
      has_changes: ${{ steps.plan.outputs.has_changes }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
          role-session-name: GitHubActionsSession
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          create_credentials_file: true
          export_environment_variables: true
          universe: googleapis.com
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          id_token_include_email: false
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0"
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        id: plan
        shell: bash
        run: |
          # -detailed-exitcode オプションを使用してplanを実行
          terraform plan -detailed-exitcode -out saved_plan
          exit_code=$?
          
          echo "Plan exit code: $exit_code"
          
          # 終了コードに基づいて変更の有無を判定
          # 0 = 変更なし
          # 1 = エラー
          # 2 = 変更あり
          if [ $exit_code -eq 2 ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          elif [ $exit_code -eq 0 ]; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "Terraform plan failed"
            exit 1
          fi
      
      - name: Upload saved plan
        uses: actions/upload-artifact@v4.6.1
        with:
          name: saved_plan
          path: saved_plan

  apply:
    name: Terraform Apply
    needs: plan
    if: needs.plan.outputs.has_changes == 'true'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Download saved plan
        uses: actions/download-artifact@v4.1.9
        with:
          name: saved_plan

      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
          role-session-name: GitHubActionsSession
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          create_credentials_file: true
          export_environment_variables: true
          universe: googleapis.com
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          id_token_include_email: false
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0"
          
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Apply
        run: terraform apply -auto-approve saved_plan
