name: aws-auth
on:
  push:
    branches:
      - "master"
 
jobs:
  aws-auth:
    name: aws-auth
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
 
    steps:
    - name: set ROLE
      run: |
        echo "AWS_ROLE_ARN=$" >> $GITHUB_ENV
 
    - name: Checkout
      uses: actions/checkout@v3
 
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: $
        aws-region: ap-northeast-1
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ~1.2.0
 
    - name: Terraform Init
      run: terraform init
      working-directory: terraform
 
    - name: Terraform plan
      run: terraform plan
      working-directory: terraform
