name: aws-auth

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  auth:
    runs-on: ubuntu-latest
    steps:
      # Google Cloud認証を実行
      - uses: google-github-actions/auth@v2
        id: auth
        with:
          project_id: "dev-ss-444303"
          workload_identity_provider:  ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          token_format: "id_token"
          id_token_audience: "sts.amazonaws.com"
      # 取得したトークンをファイルに保存
      - name: Write JWT
        run: |
          import os

          with open(os.environ["DESTINATION"], "w") as f:
            f.write(os.environ["ID_TOKEN"])
        shell: python
        env:
          DESTINATION: ${{runner.temp}}/token.txt
          ID_TOKEN: ${{steps.auth.outputs.id_token}}
      # AWS認証を実行
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'us-east-1'
          mask-aws-account-id: true
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          role-session-name: 'GitHubActions'
          web-identity-token-file: ${{runner.temp}}/token.txt
      # 認証確認
      - run: aws sts get-caller-identity
