name: aws-auth
on:
  push:
    branches:
      - "master"
jobs:
  aws-auth:
    name: aws-auth
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-northeast-1
        role-session-name: GitHubActionsSession
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ~1.2.0
    - name: Terraform Init
      run: terraform init
      working-directory: terraform
    - name: Terraform plan
      run: terraform plan
      working-directory: terraform
