name: Echo Workflow

on:
  push:
    branches-ignore:
      - master

jobs:
  echo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo Hello World
        run: echo "Hello, World"
