name: Protect Master Branch

on:
  push:
    branches:
      - master

jobs:
  prevent-push:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent direct push to master
        run: |
          echo "Direct push to master is not allowed."
          exit 1
